logging:
  pattern:
    console: "[Kafka UI Demo] %clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

server:
  port: 9009

spring:
  main:
    banner-mode: OFF
  kafka:
    listener:
      missing-topics-fatal: false
    producer:
      bootstrap-servers:
        - localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: kafka-ui-demo-cg
      auto-offset-reset: earliest
      bootstrap-servers:
        - localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    streams:
      application-id: kafka-ui-demo-sample-${random.uuid}
      bootstrap-servers:
        - localhost:9092
      properties:
        default:
          key:
            serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          value:
            serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        commit:
          interval:
            ms: 3000
        processing:
          guarantee: exactly_once_v2