logging:
  pattern:
    console: "[Kafka Connect] %clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
spring:
  application:
    name: kafka-connect-sample
  main:
    banner-mode: OFF
    log-startup-info: false
  kafka:
    listener:
      missing-topics-fatal: false
    consumer:
      group-id: kafka-connect-cg
      auto-offset-reset: earliest
      enable-auto-commit: true
      bootstrap-servers:
        - localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    streams:
      application-id: kafka-connect-sample-${random.uuid}
      bootstrap-servers:
        - localhost:9092
      properties:
        default:
          key:
            serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          value:
            serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        commit:
          interval:
            ms: 3000
        processing:
          guarantee: exactly_once_v2